<?php

declare(strict_types=1);

/**
 * @file
 * Contains \Drupal\tailwind_hmr\Hook\LibraryHooks.
 *
 * @see \Drupal\tailwind_hmr\Hook\LibraryHooks
 */
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\tailwind_hmr\Hook\LibraryHooks;
use Drupal\Core\Hook\Attribute\StopProceduralHookScan;

/**
 * Implements hook_help().
 */
function tailwind_hmr_help($route_name, RouteMatchInterface $route_match) : array { }
#[StopProceduralHookScan]

/**
 * Implements hook_library_info_alter().
 */
#[LegacyHook]
function tailwind_hmr_library_info_alter(array &$libraries, string $extension): void {
  \Drupal::service(LibraryHooks::class)->libraryInfoAlter($libraries, $extension);
}
